### ISSUE TITLE
Unity Push Notification Out-dated

### ISSUE THREAD

**Issue by kolibrigames-ajimine-vahid** [braze-inc/braze-docs#1535]
# Submit an Issue
**Describe the Problem:**
It seems like this doesn't contain details of how to configure using the automated build process with the `AppboyConfig`. 

**Related Links, Resources, Code Samples, and Images:**
https://github.com/Appboy/braze-docs/blob/develop/_docs/_developer_guide/platform_integration_guides/unity/android/push_notifications.md

### Is this change associated with a Braze feature/product/SDK release?
- [x] Yes (__Feature Release Date:__)
- [ ] No

> If yes, please note the date of the feature release.
[2.1.0](https://github.com/Appboy/appboy-unity-sdk/releases)
---
---

<details>
<summary>Before Your Submit Checklist</summary>

- [x] Fill out the relevant items under __Submit an Issue__ above.
- [ ] [Label](https://github.com/Appboy/braze-docs/issues/labels) this issue.
- [ ] Assign this issue to either yourself, the Braze Technical Writers (@Timothy-Kim and @KellieHawks), or to another appropriate person. _If you do not assign anyone to an issue, your issue may be closed or left uncompleted._
</details>

---
---

**Comment by davidbielik** [comment]
Closing as this has been resolved in recent releases.
