### ISSUE TITLE
Correct way to handle sending user custom attributes

### ISSUE THREAD

**Issue by DiSleeper** [braze-inc/braze-docs#1580]
# Submit an Issue
**Describe the Problem:**
> Is it possible to receive some callback or there can be another solution for sending user custom attributes and after that disable SDK?
The thing is that I sent a user flag "signed_out" with the boolean value true or false. And when a user signed out from the app I called the code below, but we didn't receive the last attribute, cause this operation is async but "disableSdk()" is permanent.
Is there any correct way to send user attributes and then disable SDK?

**Related Links, Resources, Code Samples, and Images:**
`appboy.currentUser?.setCustomUserAttribute("signed_out", false)
Appboy.disableSdk(appContext)`

### Is this change associated with a Braze feature/product/SDK release?
- [ ] Yes (__Feature Release Date:__)
- [ ] No

> If yes, please note the date of the feature release.

---
---

<details>
<summary>Before Your Submit Checklist</summary>

- [ ] Fill out the relevant items under __Submit an Issue__ above.
- [ ] [Label](https://github.com/Appboy/braze-docs/issues/labels) this issue.
- [ ] Assign this issue to either yourself, the Braze Technical Writers (@Timothy-Kim and @KellieHawks), or to another appropriate person. _If you do not assign anyone to an issue, your issue may be closed or left uncompleted._
</details>

---
---

**Comment by davidbielik** [comment]
Hi @DiSleeper Which SDK is this in reference to?

I suggest you raise this as a support ticket to our team, and at the same time I can help clarify our documentation
