### ISSUE TITLE
API Documentation: definition of APP_ID_OF_OS

### ISSUE THREAD

**Issue by unscriptable** [braze-inc/braze-docs#1698]
**Describe the Problem:**
We plan to push APNs tokens from our cloud services into braze.  While looking in the documentation, there are references to a cryptic value called `"APP_ID_OF_OS"`.  It's one of the required properties, `"app_id"`, of the `"push_tokens"` array in the `"attributes"` section of the payload for the `user/track` endpoint.  It would be helpful to define this value.

**Related Links, Resources, Code Samples, and Images:**
https://www.braze.com/docs/help/help_articles/push/push_token_migration/#migration-via-api

This value is shown in the code samples, but is not described in the remainder of the document.

### Is this change associated with a Braze feature/product/SDK release?
- [ ] Yes
- [x] No

I would submit a PR, but I don't know what this value is! 😄

**Comment by davidbielik** [comment]
Fixed in #2182
