### ISSUE TITLE
Canvas Data Series Analytics Endpoint

### ISSUE THREAD

**Issue by jayfunk** [braze-inc/braze-docs#1985]
@Timothy-Kim

# Submit an Issue
**Describe the Problem:**
Documentation for https://www.braze.com/docs/api/endpoints/export/canvas/get_canvas_analytics specifies that a `canvas_id` is to be supplied. The example request uses a `campaign_id`:
```
curl --location --request GET 'https://rest.iad-01.braze.com/sends/data_series?campaign_id=3bbc4555-8fa0-4c9b-a5c0-4505edf3e064&send_id=3456789&length=30&ending_at=2014-12-10T23:59:59-05:00' \
--header 'Authorization: Bearer YOUR_REST_API_KEY'
```

and when calling the endpoint with a `canvas_id` as specified results in this error:

```
{
    "message": "campaign_id must be a string of the campaign api identifier"
}
```

**Related Links, Resources, Code Samples, and Images:**

### Is this change associated with a Braze feature/product/SDK release?
- [ ] Yes (__Feature Release Date:__)
- [x] No

> If yes, please note the date of the feature release.

---
---

<details>
<summary>Before Your Submit Checklist</summary>

- [x] Fill out the relevant items under __Submit an Issue__ above.
- [x] [Label](https://github.com/Appboy/braze-docs/issues/labels) this issue.
- [x] Assign this issue to either yourself, the Braze Technical Writers ( #@Timothy-Kim and @KellieHawks), or to another appropriate person. _If you do not assign anyone to an issue, your issue may be closed or left uncompleted._
</details>

---
---

**Comment by jayfunk** [comment]
Issue turned out to only be a documentation issue. Submitting a PR to fix the documentation.

**Comment by Samalmohanna1** [comment]
@jayfunk Could you share what was wrong in the documentation please. Currently having a similar issue that results in the same error message.
