### ISSUE TITLE
add hmac_sha256

### ISSUE THREAD

**Issue by scortellino** [braze-inc/braze-docs#2270]
# Submit an Issue
**Describe the Problem:**

@timothy-kim 
 Is it possible to add hmac_sha256? I only see hmac for sha1. I know it's possible from native shopify liquid template. I'm trying to use a connected content and it requires to use hmac_sha256 for the authorization.

Thanks.

### Is this change associated with a Braze feature/product/SDK release?
- [ ] Yes (__Feature Release Date:__)
- [ x] No

**Comment by KellieHawks** [comment]
@bre-fitzgerald Might be worth adding this filter to the documentation you are building

**Comment by scortellino** [comment]
@KellieHawks thank you for the quick response! Forgive me if I sound I'm giving pressure, but do we have an ETA when this feature will be available?

**Comment by KellieHawks** [comment]
@scortellino It's hard to give an exact date, but I have confirmed with our engineers that this functionality has been added to our platform code. I believe they are testing it and will release it very soon! I can follow up as I hear more!

**Comment by KellieHawks** [comment]
@scortellino Following up on your inquiry about the hmac_sha256 filter, it is now available on the platform and ready to use! The [documentation](https://www.braze.com/docs/user_guide/personalization_and_dynamic_content/liquid/advanced_filters/) will be updated later today to reflect these changes. 

Here is the [PR](https://github.com/braze-inc/braze-docs/pull/2288/files) if you'd like to take a look while we update the documentation.

**Comment by scortellino** [comment]
Thank you @KellieHawks !
