### ISSUE TITLE
connected content: instructions for special character escaping for POST body?

### ISSUE THREAD

**Issue by ArthurFlageul** [braze-inc/braze-docs#2432]
# Submit an Issue
**Describe the Problem:**

I'm trying to send a POST request to an authentication endpoint according to this [page](https://github.com/braze-inc/braze-docs/blob/develop/_docs/_user_guide/personalization_and_dynamic_content/connected_content/local_connected_content_variables.md
).

I'm using the following bit:

```
{% connected_content
    https://myendpoint/v1/sessions
    :method post
    :headers {
      "Content-Type": "application/json",
 	  }
    :body email=email+api@me.com&password=p8x&y%rXMX
    :cache 900
    :save token_response
%}
```
But I'm not getting any response in `token_response`. I'm suspecting that it might be related to special characters in my email address and password but nothing is said in the docs about this.  The same content as curl works fine. 

Do you have any guidance to provide?

Thanks!

### Is this change associated with a Braze feature/product/SDK release?
- [ ] Yes (__Feature Release Date:__)
- [x] No

<details>
<summary>Before Your Submit Checklist</summary>

- [x] Fill out the relevant items under __Submit an Issue__ above.
- [ ] [Label](https://github.com/Appboy/braze-docs/issues/labels) this issue.
- [ ] Assign this issue to either yourself, the Braze Technical Writers (@Timothy-Kim and @KellieHawks), or to another appropriate person. _If you do not assign anyone to an issue, your issue may be closed or left uncompleted._
</details>

---
---

**Comment by ArthurFlageul** [comment]
@KellieHawks or anyone, any idea? 🙂

**Comment by KellieHawks** [comment]
@ArthurFlageul I submitted an internal tech support request for some guidance on your issue. Hopefully, in the coming days, I'll have something to report back. I'll keep you posted.

**Comment by KellieHawks** [comment]
Hey @ArthurFlageul, just following up. Please go onto the Braze dashboard and submit a support ticket, this question, unfortunately, falls outside the scope of what the Braze documentation team can help with. Our support team will be able to help answer your question. Thanks!
<img width="758" alt="Screen Shot 2021-07-27 at 11 38 16 AM" src="https://user-images.githubusercontent.com/47005843/127183922-7a2168c2-961f-4e2e-9938-17a3caadd983.png">
