### ISSUE TITLE
Outdated AndroidX documentation page

### ISSUE THREAD

**Issue by janselv** [braze-inc/braze-docs#2513]
**Target page**: [androidx_integration/#braze-androidx-module](https://www.braze.com/docs/developer_guide/platform_integration_guides/android/advanced_use_cases/androidx_integration/#braze-androidx-module)

I think that the instructions on this page are a bit misleading. It state that `ui-x` is available **from** `3.0.0` but it seems that support was dropped for further versions. e.g When you try to apply `ui-x` dependency with `v15+`, dependency resolution fails and when you browse [android-sdk-ui-x](https://appboy.github.io/appboy-android-sdk/sdk/com/appboy/android-sdk-ui-x/) directory, the latest version there is `6+`.

I think the page needs to be updated as the standard Braze UI library already uses JetPack libs.

**Comment by radixdev** [comment]
Hi @janselv ,

This page is indeed outdated and we will be removing it in the future.
