### ISSUE TITLE
Postman Collection Out of Date

### ISSUE THREAD

**Issue by SimeonBraze** [braze-inc/braze-docs#3093]
The Braze Postman collection shown [here](https://github.com/braze-inc/braze-docs/blob/develop/_docs/_api/postman_collection.md) does not include the new SMS endpoints for invalid numbers.

I have created an updated postman collection that also standardized variable names and cleans up authorisation you are welcome to use if you like.
[Braze Collection](https://drive.google.com/file/d/13shAYXXj9REcH9QvyD62pOO_C5ZsF9_U/view?usp=sharing)
[Matching Environment Variables](https://drive.google.com/file/d/13pnQbFmNthnu81QJ_4TKdt0Xid9J9nvs/view?usp=sharing)

**Comment by KellieHawks** [comment]
Hello @SimeonBraze, thanks for the call out! We plan on adding those to the collection by the end of the day today. 
-The Braze documentation team
