### ISSUE TITLE
Push Stories OS/SDK version requirement is unclear

### ISSUE THREAD

**Issue by trevinoa** [braze-inc/braze-docs#3485]
Hi folks! [This page on Push Stories](https://www.braze.com/docs/user_guide/message_building_by_channel/push/advanced_push_options/push_stories/#push-story-composer) says:

> Users must update to the latest version of Android (version 2.2.0+) and iOS (version 3.2.0+) to receive Push Stories.

I believe this refers to our SDK versions, but that's not clear. Assuming it's referring to Braze SDK versions, the page doesn't comment on iOS/Android OS versions required to display Push Stories.

**Comment by davidbielik** [comment]
#3497 

<img width="605" alt="image" src="https://user-images.githubusercontent.com/7410770/165615688-602892ab-b0cf-4ea2-a2c5-19cc1a38afe0.png">
