### ISSUE TITLE
Custom attributes - Object data type support

### ISSUE THREAD

**Issue by mohatallah** [braze-inc/braze-docs#3757]
The custom attributes page has this message: "Coming soon! Generally available support for object and object array data types is arriving in Spring 2022.". We might want to update the messaging to reflect the latest status of that as it currently states "Coming soon in Spring 2022" which has elapsed.

https://www.braze.com/docs/user_guide/data_and_analytics/custom_data/custom_attributes/#:~:text=Coming%20soon!%20Generally%20available%20support%20for%20object%20and%20object%20array%20data%20types%20is%20arriving%20in%20Spring%202022.

**Comment by KellieHawks** [comment]
Thanks for flagging!
