### ISSUE TITLE
Technical Question

### ISSUE THREAD

**Issue by lzhuor** [braze-inc/braze-docs#3775]
Dear Braze Team,

I have a question regarding this page: [User Profile Lifecycle](https://github.com/braze-inc/braze-docs/blob/develop/_docs/_user_guide/data_and_analytics/user_data_collection/user_profile_lifecycle.md).

In the section of **Advanced use case information**, we have:
```
If you attempt to set a pre-existing external_id on an anonymous user profile which share a matching alias name, but have different labels, only the alias label on the pre-existing known user profile will be maintained.
```
Could you please elaborate more on this with an example? That will be very helpful. Thank yo very much!

**Comment by KellieHawks** [comment]
Hey @lzhuor, please fill out a [Braze support ticket](https://www.braze.com/docs/support_contact/) and we will be happy to provide you with more context! Thanks in advance!
