### ISSUE TITLE
Specify what it means to "receive a specific Canvas component"

### ISSUE THREAD

**Issue by weenzeel** [braze-inc/braze-docs#4042]
Don't know if this is the right way to Contact Braze about a documentation page that could be more clear ...

On the page https://www.braze.com/docs/user_guide/engagement_tools/segments/segmentation_filters I didn't understand what "receive a specific Canvas component" meant for the filter Received Canvas Step.

I did a test for IAM messages. And it looks like an IAM needs to be displayed for the user to count as a "Received Canvas Step". It's not enough that the customer has advanced to the message component.

Perhaps this could be clarified in the docs? And it would be helpful to know how other channels are accounted for as well.

Thanks!

**Comment by lydia-xie** [comment]
Hi @weenzeel! Thanks for bringing this to our attention. I'll go ahead and update the related docs for more clarity. 👍
