### ISSUE TITLE
SCIM API - Incomplete App Group Permissions 

### ISSUE THREAD

**Issue by SimeonBraze** [braze-inc/braze-docs#4321]
The [SCMI API Appendix](https://www.braze.com/docs/scim_api_appendix/#company-permission-strings) page is missing the value for the dashboard permission ["View User Profiles PII Compliant"](https://p15.zdusercontent.com/attachment/2436592/pJyRt0HxD2Y67gt4njKA8QlEI?token=eyJhbGciOiJkaXIiLCJlbmMiOiJBMTI4Q0JDLUhTMjU2In0..btg3hAQAFUV6gfSL3prbHw.vMSLiAyUtndo7EZ33sfd0r3Q_DLEmKyLKsS-TcWdmNhQ-okgijZpTG6KYjwf4Re_oFTLppwT06rZ91iPeYng766oRQ6_QH2OJsQIDywUVtpymBdh6BsJB0I-D_TOTBrmBQ2xJmj3f1dU958_4G9SrpE23BKsXBIDeD-9NXxK5zH7tnXDhnp8J4jZcqHLoKqG1ZQIouk7YUVwjijIApxH6sS_Uf0XVcj-4NLyXfwiMAvfK-trSDCl6IL-tBMcMJCy9PteNZHN9VPdffUwGLBI8OkGlXxJ43FicZGs1ECw8Qw.U12QXS1oT6aUd0lXsmCnvw). What is the correct value to modify this?

- [ ] Fill out the relevant items under **Submit an Issue** above.
- [ ] [Label](https://github.com/Appboy/braze-docs/issues/labels) this issue.
- [ ] Assign this issue to either yourself, the Braze Technical Writers (@Timothy-Kim and @KellieHawks), or to another appropriate person. _If you do not assign anyone to an issue, your issue may be closed or left uncompleted._
</details>

---

**Comment by KellieHawks** [comment]
Resolved in this PR: https://github.com/braze-inc/braze-docs/pull/4322#pullrequestreview-1160127515
