### ISSUE TITLE
Code error on documentation picture

### ISSUE THREAD

**Issue by bbolek** [braze-inc/braze-docs#4466]
Navigate to the Braze support contact page for guidance on these issues: [https://www.braze.com/docs/support_contact/](https://www.braze.com/docs/support_contact/)

The Braze documentation team can only support documentation-related issues. 
**All technical questions, bugs, and general issues will be closed**.

At page https://github.com/braze-inc/braze-docs/blob/develop/_docs/_user_guide/data_and_analytics/user_data_collection/best_practices.md;

First curly brace in attributes array is wrong.  It should be start object, not end object
![image](https://user-images.githubusercontent.com/1146456/204808368-d02e0538-d9ec-4e1f-adb6-d3e20db7f2a7.png)

Thank you

**Comment by KellieHawks** [comment]
Thanks for tagging @bbolek, we will make sure this gets updated. 
- Braze docs team
