### ISSUE TITLE
Clarify behaviour of Merge Users endpoint

### ISSUE THREAD

**Issue by stuartpullinger** [braze-inc/braze-docs#5012]
Thanks for providing all this documentation and putting it on Github so I can raise my issue!

After reading the Merge Users endpoint documentation, I have come up against some things I still don't understand.
[markdown](https://github.com/braze-inc/braze-docs/blob/develop/_docs/_api/endpoints/user_data/post_users_merge.md) | [html](https://www.braze.com/docs/api/endpoints/user_data/post_users_merge/)

- The [request parameters](https://www.braze.com/docs/api/endpoints/user_data/post_users_merge/#request-parameters) box names the `identifier_to_merge` and the `identifier_to_keep` parameters. In the next paragraph, they are called the 'original user' and 'target user'. It's not clear to me which term maps onto which: the use of 2 different terms for the same things is a bit confusing.
- It's not clear to me how nested objects (eg. custom attributes) are merged. If user A has a custom attribute 'marketing_preferences' with a value of `{email: True, SMS: False}` and user B has 'marketing_preferences' of `{email: False, Phone: True}`, what is the result of merging B into A? What if B's 'marketing_preferences' is an empty object? A few examples would help, I think.
- Finally, having an `identifier_to_keep` suggests that the other identifier might not be kept. I presume that the `identifier_to_merge` is not deleted but it might help to be explicit about whether it is the API user's responsibility to do this.

Many thanks for your time.

**Comment by lydia-xie** [comment]
Addressed issue in https://github.com/braze-inc/braze-docs/pull/5134
