### ISSUE TITLE
Problem with External Id Removal Documentation

### ISSUE THREAD

**Issue by kacheo** [braze-inc/braze-docs#5065]
There is a error in this doc: https://github.com/braze-inc/braze-docs/blob/34b466133c77f1e34959a9d16a671d6ee3cf31e3/_docs/_api/endpoints/user_data/external_id_migration/post_external_ids_remove.md

The response example looks to be from external id rename example not actual external id removal. Please update the response to be correct.

**Comment by KellieHawks** [comment]
https://github.com/braze-inc/braze-docs/pull/5081
