### ISSUE TITLE
API Trigger Parameter Style Not Applied

### ISSUE THREAD

**Issue by ananthuuu** [braze-inc/braze-docs#5630]
### Bug Description:
When utilizing the API trigger feature in Braze and attempting to apply styling to a parameter, such as font color, background color, or font size, the specified styles are not reflected in the output. Specifically, when attempting to apply a bold style to the in   API trigger parameters within a template, the styling is not being reflected in the final output.

### Example Code Snippet:
Consider the following code snippet where we attempt to stylize the user_email parameter with bold formatting:

`{{api_trigger_properties.${user_email} | default: 'MISSING_FIRST_NAME'}}`
### Expected Result:
Upon applying the bold style using the editor for the entire 
`{{api_trigger_properties.${user_email} | default: 'MISSING_FIRST_NAME'}} `
expression, the **user_email** parameter should be displayed in bold in the resulting output.

### Actual Result:
Unfortunately, despite applying the bold style using the editor, the user_email parameter remains unaffected. The output displays the user_email parameter in its default appearance, without any bold formatting.

### Additional Information:

This issue persists across different environments and browsers, suggesting that it is not specific to a particular configuration.
I have reviewed the Braze documentation thoroughly to ensure that I am correctly applying the bold style as per the provided guidelines.. I greatly appreciate your attention to this matter, as it impacts our ability to deliver a consistent and visually appealing user experience for our customers.

**Comment by KellieHawks** [comment]
Hey @ananthuuu, thanks for flagging this bug. Unfortunately, the tech support team would be a better place to get this issue fixed. Would you mind filling out a support request? https://www.braze.com/docs/support_contact

Closing this issue. Thanks!
