### ISSUE TITLE
Fire OS integration guide: wrong path for api_key.txt?

### ISSUE THREAD

**Issue by cpele** [braze-inc/braze-docs#5732]
The documentation instructs to place the `api_key.txt` resource file in the `Assets/Plugins/Android/assets` directory but this doesn't seem correct. I think it should be `app/src/fire/assets`.

See https://github.com/braze-inc/braze-docs/blob/f3dcc70626b04deb0db779c56cd6b6b4658b3882/_docs/_developer_guide/platform_integration_guides/android/push_notifications/fireos/integration.md?plain=1#L92C9-L92C9

**Comment by josh-mccrowell-braze** [comment]
Hi there. Thank you for raising this issue!

I reached out to our Engineering team about this subject and received this response:
> Either location would be correct. The former location (`..Android/assets`) when items are placed in it tells Unity to move it to the `app/src/VARIANT/assets` folder automatically. So you could place it there manually or just put it at `Assets/Plugins/Android/assets` for convenience. `VARIANT`, in this instance, being `fire`, but it could be `main`, `debug`, etc.

I hope this makes sense. I'm going to close this issue, but if you're seeing differing behavior or have any concerns, please reach back out. 

Again, thanks so much for raising the issue!
