### ISSUE TITLE
Suggested documentation change to prevent misconfiguration of ADM push-notifications registration

### ISSUE THREAD

**Issue by cpele** [braze-inc/braze-docs#5802]
I spent a few days figuring out why the Braze broadcast receiver wasn't receiving broadcasts from ADM (Amazon Device Messaging) when I was testing push notifications to my Fire tablet...

It was because I didn't enable the `exported` flag in the Android manifest. 

It had to be e.g.:
```xml
<application>
    <amazon:enable-feature
        android:name="com.amazon.device.messaging"
        android:required="false"/>
    <receiver
        android:name=".CustomBrazeAmazonDeviceMessagingReceiver"
        android:exported="true"
        android:permission="com.amazon.device.messaging.permission.SEND">
        <intent-filter>
            <action android:name="com.amazon.device.messaging.intent.RECEIVE" />
            <action android:name="com.amazon.device.messaging.intent.REGISTRATION" />
            <category android:name="${applicationId}" />
        </intent-filter>
    </receiver>
</application>
```

This kind of misconfiguration can be prevented by documenting this in the documentation and explicitly setting the `exported` flag to `true` in the sample snippet:

https://github.com/braze-inc/braze-docs/blob/d3602abce1f1db9236112439f843ca9bac2a627d/_docs/_developer_guide/platform_integration_guides/android/push_notifications/fireos/integration.md?plain=1#L78C18-L78C18

**Comment by josh-mccrowell-braze** [comment]
Hi @cpele . Thank you very much for raising this issue. We have updated the docs based on your feedback. These changes will be included in our next deploy, which occur twice a week on Tuesdays and Thursdays at 3 PM EST. Once deployed, changes may take up to 24 hours to appear on braze.com/docs.
