### ISSUE TITLE
API request URL is not correct

### ISSUE THREAD

**Issue by DennisMaas** [braze-inc/braze-docs#6108]
https://github.com/braze-inc/braze-docs/blob/c431955fc6cf1c9d9df1b28cdd3b4c586d8a9e85/_docs/_partners/message_personalization/location/accuweather.md?plain=1#L71C21-L71C21

Line 1 and 3 in braze's code example are using `http://api.accuweather.com` as host name. The correct hostname is `dataservice.accuweather.com`.

**Comment by josh-mccrowell-braze** [comment]
Thanks for raising the issue, Dennis! We're looking into it.

**Comment by lydia-xie** [comment]
Hey @DennisMaas - I've updated the API request URL in #6120 and #6121. These changes will be included in our deploy tomorrow (9/12) and should be visible in 24 hours. Thanks again for flagging this!
