### ISSUE TITLE
Example in the Link aliasing for URLs generated via Liquid section

### ISSUE THREAD

**Issue by nmandel** [braze-inc/braze-docs#6524]
The example from the [Link aliasing for URLs generated via Liquid section](https://www.braze.com/docs/user_guide/message_building_by_channel/email/templates/link_aliasing/?tab=drag-and-drop%20editor#examples:~:text=before%20the%20anchor.-,Link%20aliasing%20for%20URLs%20generated%20via%20Liquid,-For%20URLs%20that) could use a couple updates, based on my testing. As stands, the example is:

```html
{% assign link1 = https://www.braze1.com %}

<a href="{{link1}}?">{{link1}}?</a>
```

But there are two things that should probably change:
1. The link in the assignment should be wrapped in quotes, otherwise it won't show up.
2. Less important, but we don't need the second `?` in the `<a/>` element, because that's only the text that you click on to visit the link, not the link itself.

I think it should look like:

```html
{% assign link1 = "https://www.braze1.com" %}

<a href="{{link1}}?">{{link1}}</a>
```

(You can test this out in e.g. Preview & Test using the HTML Email editor)

**Comment by josh-mccrowell-braze** [comment]
Hey @nmandel ! 

This is a really valuable insight. Thank you! So we can track this work, would you mind submitting this as a [docs request](http://www.braze.com/docs/request) for our tracking purposes? 

Thanks again!
Josh - Tech Writing Team

**Comment by nmandel** [comment]
Ah yes, will do! I did wonder if I chose the wrong feedback avenue. 😅

**Comment by nmandel** [comment]
https://jira.braze.com/browse/BD-2603

**Comment by josh-mccrowell-braze** [comment]
Thank you! Whatever gets us connected works for us. 

Appreciate it.
