### ISSUE TITLE
Add explicit instruction to enable "Firebase Cloud Messaging API (V1)" in Android push integration docs

### ISSUE THREAD

**Issue by hseitz** [braze-inc/braze-docs#6806]
The Android push integration docs have recently been updated to reflect the sunsetting of the Legacy Cloud Messaging API in favor of the Firebase Cloud Messaging API (V1). However, there is not an explicit instruction to enable this API through the Firebase Console. This will be required in order to send messages via FCM.

**Comment by josh-mccrowell-braze** [comment]
Thank you for submitting this as a Docs task! Since we'll track it on that end, I will go ahead and close this issue.
