### ISSUE TITLE
CURL commands are missing trailing characters

### ISSUE THREAD

**Issue by m-larue** [braze-inc/braze-docs#6928]
> This template is for submitting tool-related issues such as broken links, missing images and content, incorrect CSS styling, broken Liquid tags, and more. To request a docs feature, see [Request a feature](https://github.com/braze-inc/braze-docs/issues/new?assignees=&labels=enhancement&projects=&template=request_a_feature.md&title=).

### Issue description
Example CURL commands are missing some trailing characters: }'

### Reproduce the issue

Here's how you reproduce the issue:

1. Navigate to https://www.braze.com/docs/help/help_articles/push/push_token_migration/#manual-migration-via-api
2. View the first and second example CURL commands
3. Observe that there is no closing curly-brace, and no closing single-quote. 

Alternately, you can try copy-pasting the command in your terminal and seeing that it prompts you to continue typing (as opposed to running the command)

### Additional information (optional)

Current:
```
Copied
curl --location --request POST 'https://rest.iad-01.braze.com/users/track' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer YOUR-API-KEY-HERE' \
--data-raw '{
"attributes" : [
  {
	"push_token_import" : false,
	"external_id": "example_external_id",
	"country": "US",
	"language": "en",
	"YOUR_CUSTOM_ATTRIBUTE": "YOUR_VALUE",
	"push_tokens": [
	  {"app_id": "APP_ID_OF_OS", "token": "PUSH_TOKEN_STRING"}
	]
  }
]
```

Expected:
```
Copied
curl --location --request POST 'https://rest.iad-01.braze.com/users/track' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer YOUR-API-KEY-HERE' \
--data-raw '{
"attributes" : [
  {
	"push_token_import" : false,
	"external_id": "example_external_id",
	"country": "US",
	"language": "en",
	"YOUR_CUSTOM_ATTRIBUTE": "YOUR_VALUE",
	"push_tokens": [
	  {"app_id": "APP_ID_OF_OS", "token": "PUSH_TOKEN_STRING"}
	]
  }
]
}'
```

#### Screenshots:

- N/A

#### Computer specifications:

- Device: N/A
- OS: N/A
- Browser: N/A
- Version: N/A

**Comment by internetisaiah** [comment]
Hey @m-larue , thanks for raising this issue! I'll be working on a fix today 👍🏽

**Comment by internetisaiah** [comment]
@m-larue , the fix has been deployed and should be live by tomorrow!
