### ISSUE TITLE
Nested Objects documentation missing section

### ISSUE THREAD

**Issue by shawnhuynh** [braze-inc/braze-docs#7228]
### Issue description
This [documentation](https://github.com/braze-inc/braze-docs/blob/develop/_docs/_user_guide/data_and_analytics/custom_data/custom_events/nested_objects.md) references "Event property segmentation" as a section for content under Step 2 but there is no corresponding content/examples.

### Reproduce the issue
In this [Step 2](https://www.braze.com/docs/user_guide/data_and_analytics/custom_data/custom_events/nested_objects/#step-1-generate-a-schema:~:text=the%20%20plus%20button.-,Step%202%3A%20Use%20the%20nested%20object,-After%20generating%20a) there's a list of sections and the documentation essentially ends at "Personalization"

#### Screenshots:
<img width="1047" alt="image" src="https://github.com/braze-inc/braze-docs/assets/80064326/4eb9407f-65c4-496d-967b-1d69cc103b1f">

**Comment by josh-mccrowell-braze** [comment]
@shawnhuynh Thank you for raising this issue. We addressed this by removing the listing without corresponding examples in this PR: https://github.com/braze-inc/braze-docs/pull/7229
