### ISSUE TITLE
Add generic documentation for structure of batch API requests

### ISSUE THREAD

**Issue by Munhuggas** [braze-inc/braze-docs#7410]
### Feature description
In a previous request last week [I asked for documentation on how to structure batch API requests](https://github.com/braze-inc/braze-docs/issues/7397#issuecomment-2128627927) since the documentation mentions them being available. Now I would love to see either documentation on each endpoint how to structure the requests or some kind of overview on how they are generally structured.

### Ways to implement (optional)
Add something similar [as the example batch request](https://braze-docs-b7seayh50-braze.vercel.app/api/api_limits/) but for every endpoint. It is not obvious from what I have found in the documentation what the group entity (in this example `subscription_groups: [...]`) is named for other batch calls.

Another way to solve this would be to just add what the batch node (`subscription_groups` in the example above) is for each call in the API description.

**Comment by Munhuggas** [comment]
Maybe I have misunderstood the documentation? From the example I surmised that you can batch multiple requests in some unknown format. But do you actually mean that sending 50 recipients at a time to the `campaigns/trigger/send` endpoint is in fact the batching you are talking about?

**Comment by internetisaiah** [comment]
Hello @Munhuggas , apologies for the delay! We are looking into this and will get back to you with an update soon. Thanks for submitting the request!

**Comment by lydia-xie** [comment]
Hi @Munhuggas, thanks for the great feedback! We're currently in the process of reviewing and updating our API docs, and we've noted this as a gap in our example requests. In the meantime, we've created a ticket to address the batch API call example requests and will close this out in the future when the work is complete. Feel free to let us know if you have any additional questions.

**Comment by Munhuggas** [comment]
Thanks for getting back to me and thanks for going the extra mile trying to improve the docs! 🙏

**Comment by josh-mccrowell-braze** [comment]
Hi @Munhuggas, 
Thanks again for opening this request! The Braze Docs team is currently working on overhauling the API Guide section of our documentation to provide an overall improvement to the user experience (we hope!). I believe these general improvements will speak to the core of your request. As such, I'm going to resolve this issue. 

Thanks again for getting in touch. Please reach out if you have any questions.
Thanks!
The Braze Docs team
