### ISSUE TITLE
No "Float" or "String" datatype information in custom attribute table

### ISSUE THREAD

**Issue by el-veee** [braze-inc/braze-docs#7961]
### Issue description
In this location, the `Floats` entry in the custom attributes table is empty: https://github.com/braze-inc/braze-docs/blob/62d1ba27a6a1d52b0902cc538b10df0f170b5bd4/_docs/_api/objects_filters/user_attributes_object.md?plain=1#L88

Can we get some information published for the handling of floats? 

### Reproduce the issue
Go to https://github.com/braze-inc/braze-docs/blob/62d1ba27a6a1d52b0902cc538b10df0f170b5bd4/_docs/_api/objects_filters/user_attributes_object.md?plain=1#L88

#### Computer specifications:

- Device: N/A
- OS: N/A
- Browser: N/A
- Version: N/A

**Comment by el-veee** [comment]
Also the "String" entry in that table is missing https://github.com/braze-inc/braze-docs/blob/62d1ba27a6a1d52b0902cc538b10df0f170b5bd4/_docs/_api/objects_filters/user_attributes_object.md?plain=1#L90

**Comment by el-veee** [comment]
"Booleans" is also empty for the Event object https://github.com/braze-inc/braze-docs/blob/62d1ba27a6a1d52b0902cc538b10df0f170b5bd4/_docs/_api/objects_filters/event_object.md?plain=1#L66

**Comment by lydia-xie** [comment]
Hey @el-veee - thanks for reaching out about this! This has been resolved with this [PR](https://github.com/braze-inc/braze-docs/pull/7965).
