### ISSUE TITLE
Update Apple and Android object docs to include use_webview

### ISSUE THREAD

**Issue by mhaviv** [braze-inc/braze-docs#8521]
### Feature description
Update the documentation for Apple Object and Android Object to include use_webview attribute when leveraging API only
Currently this attribute is missing in the docs and it does work to modify the context received with a braze integration to open the webview from the push notification in app or externally. 
Apple Object: https://www.braze.com/docs/api/objects_filters/messaging/apple_object/#apple-push-object
Android Object: https://www.braze.com/docs/api/objects_filters/messaging/android_object/#android-push-object

**Comment by josh-mccrowell-braze** [comment]
Hi @mhaviv ! Thanks for raising this request. I'll review it with the team and see if we can update that documentation.

**Comment by lydia-xie** [comment]
Hi @mhaviv ! I've created a [PR](https://github.com/braze-inc/braze-docs/pull/8576) to update our Android and iOS object articles based on your feedback. This edit will be live later today. Closing this issue. Thanks again!
